[[redirects]]
  from = "/script.js"
  to = "https://api.pirsch.io/pa.js"
  status = 200
  force = true
  headers = {Host = "api.pirsch.io"}

[[redirects]]
  from = "/p/pv"
  to = "https://api.pirsch.io/api/v1/hit"
  status = 200
  force = true
  headers = {Host = "api.pirsch.io"}

[[redirects]]
  from = "/p/e"
  to = "https://api.pirsch.io/api/v1/event"
  status = 200
  force = true
  headers = {Host = "api.pirsch.io"}

[[redirects]]
  from = "/p/s"
  to = "https://api.pirsch.io/api/v1/session"
  status = 200
  force = true
  headers = {Host = "api.pirsch.io"}
